create table if not exists public.qa_run_inputs (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.qa_runs(id) on delete cascade,
  row_index integer not null,
  production_url text not null default '',
  staging_url text not null default '',
  created_at timestamptz not null default now(),
  unique (run_id, row_index)
);

create index if not exists qa_run_inputs_run_idx
  on public.qa_run_inputs (run_id, row_index);
